# Generated by Django 5.0.4 on 2024-04-16 12:54

import apps.tms.models
from apps.tms.generators import generate_model_custom_id
import django.core.validators
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(db_index=True, default=functools.partial(generate_model_custom_id, *(), **{'custom_id_field_name': 'load_id', 'default_value': 2000, 'model_name': 'BookedLoad'}), max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('heading_to_the_pickup', 'HEADING_TO_THE_PICKUP'), ('loading', 'LOADING'), ('on_route', 'ON_ROUTE'), ('unloading', 'UNLOADING'), ('delivered', 'DELIVERED'), ('invoiced', 'INVOICED'), ('cancelled', 'CANCELLED'), ('completed', 'COMPLETED'), ('voided', 'VOIDED')], max_length=255)),
                ('pickup_location', models.CharField(max_length=30)),
                ('delivery_location', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pallets_quantity', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pallets_weight', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_rate', models.IntegerField(default=None)),
                ('driver_rate', models.IntegerField(default=None)),
                ('invoice_id', models.CharField(db_index=True, default=None, max_length=8, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sprinter', 'Sprinter'), ('small straight', 'Small Straight'), ('large straight', 'Large Straight')], max_length=255)),
                ('weight', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Billing',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tms.bookedload',),
        ),
        migrations.AddField(
            model_name='bookedload',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.broker'),
        ),
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookedload',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.dispatcherprofile'),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(db_index=True, default=functools.partial(generate_model_custom_id, *(), **{'custom_id_field_name': 'unit_id', 'default_value': 1000, 'model_name': 'DriverProfile'}), max_length=6, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tms.truck')),
            ],
        ),
        migrations.AddField(
            model_name='bookedload',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.driverprofile'),
        ),
        migrations.AddField(
            model_name='bookedload',
            name='supported_truck_kind',
            field=models.ManyToManyField(to='tms.truck'),
        ),
    ]
