# Generated by Django 5.0.4 on 2024-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='mc_number',
            field=models.CharField(default=2587962, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='address',
            field=models.CharField(default='2200 Sunny St apt 4B Columbus OH', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_licence',
            field=models.CharField(default='KC896547', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(default='7854129635', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='kind',
            field=models.CharField(choices=[('sprinter', 'Sprinter'), ('small_straight', 'Small Straight'), ('large_straight', 'Large Straight')], max_length=255),
        ),
    ]
