# Generated by Django 5.0.4 on 2024-04-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_broker_mc_number_driverprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedload',
            name='supported_truck_kind',
        ),
    ]
